version: '3.8'

services: 
    service-throttle-backend:
        build: ./Service-Throttle-Backend/service-throttle-backend
        image: ravdsn/service-throttle-backend:v1.0
        ports: 
            - '8081:8081'
        container_name: service-throttle-backend
