version: "3.8"

services:
  service-throttle-mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_DATABASE=service_throttle
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root
    ports:
      - "3307:3306"
    container_name: service-throttle-mysql

  service-throttle-backend:
    restart: always
    build: ./Service-Throttle-Backend/service-throttle-backend
    image: ravdsn/service-throttle-backend:v1.0
    environment:
      - spring.datasource.url=jdbc:mysql://service-throttle-mysql:3306/service_throttle
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8081:8081"
    container_name: service-throttle-backend

  service-throttle-frontend-admin:
    restart: always
    build: ./Service-Throttle-Frontend/service-throttle-admin-dashboard
    image: ravdsn/service-throttle-frontend-admin:v1.0
    ports:
      - "3001:3000"
    container_name: service-throttle-frontend-admin
