server:
  port: 8081

spring:
  application:
    name: service-throttle-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_throttle
    username: root
    password: root
    intialize: true
  jpa:
    properties:
      hibernate:
        dialate: org.hibernate.dialect.MySQL5InnoDBDialate
    hibernate:
      ddl-auto: update
    generate-ddl: true