server:
  port: 8081

spring:
  application:
    name: service-throttle-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/service-throttle
    username: postgres
    password: root
    intialize: true
  jpa:
    properties:
      hibernate:
        dialate: org.hibernate.dialect.MySQL5InnoDBDialate
    hibernate:
      ddl-auto: create