server:
  port: 8080

spring:
  application:
    name: st-auth-api-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_throttle_data_warehouse
    username: root
    password: root
    intialize: true
  jpa:
    properties:
      hibernate:
        dialate: org.hibernate.dialect.MySQL5InnoDBDialate
    hibernate:
      ddl-auto: update
    generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

zuul:
  routes:
  host:
    socket-timeout-millis: 30000